aspwork/aspwork/Controllers/topicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPwork.Controllers
{
    public class topicController : System.Web.Mvc.Controller
    {
        // GET: Zone
        public ActionResult list(int subject)
        {
            ViewBag.subject = subject;
            return View();
        }

        [Filler.userfiller]
        public ActionResult Post()
        {

            return View();
        }

        [HttpPost]
        [Filler.userfiller]
        public ActionResult Post(string title,string content)
        {
            return View();
        }
    }
}

aspwork/aspwork/Views/topic/Post.cshtml
@{
    ViewBag.Title = "Post";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/kindeditor/kindeditor-all-min.js"></script>
<script src="~/kindeditor/kindeditor-all.js"></script>
<script type="text/javascript">
    //KindEditor脚本
    var editor;
    KindEditor.ready(function(K) {
        editor = K.create('#editor_id', {
        });
    });
</script>

<h3>发帖</h3>
@using (Html.BeginForm("Post", "topic", FormMethod.Post))
{
    Html.DropDownList("TUID", "");
        <span>标题:</span><input type="text" name="title" size="35">
                   <textarea id="editor_id" name="content" style="width:700px;height:300px;"></textarea>
    <input type="submit" value="发布">
}

aspwork/aspwork/Views/topic/list.cshtml
@{
    ViewBag.Title = "list";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<a href="/topic/Post">
    <input type=button value="发帖">
</a>
<h3>主题</h3>
<div><table width="1006" height="29" cellpadding="0" cellspacing="0">
    <tbody>

        @{  DBhelperBase db = new DBhelperBase();
            string result = string.Empty;
            string sql = "select * from BBSTopic where TSID="+ViewBag.subject;
            System.Data.DataTable table = db.GetTable(sql);

        }
        @foreach (System.Data.DataRow row in table.Rows)
        {
            <tr>

                <th width="283" >


                    <em>[ 标题：@row["TTpoic"]]</em> 1

                </th>
                <td width="388" >
                    <cite>
                        回复： @row["TReplyCount"]
                    </cite>
                    <em><span>2018-11-21</span></em>
                </td>
               <td width="100" class="num">614</td>
                <td width="225" class="by">
                    <cite>小张王</cite>
                    <em>2018-11-21 00:36</em>
                </td>
            </tr>

        }
    </tbody>
</table></div>